slurmstepd: info: Setting TMPDIR to /scratch/10933989. Previous errors about TMPDIR can be discarded
Slurm job started at 10/03/2025_11:14:14 PM

In transit.
Initing Ray (1 head node + 4 worker nodes + 4 simulation nodes) on nodes: 
	ilk-120 ilk-121 ilk-122 ilk-123 ilk-127 ilk-133 ilk-134 ilk-135 ilk-138
Head node: 172.30.203.24:6379


RAY_DEPLOY_TIME:     23.82216
2025-03-10 23:14:42,266	INFO packaging.py:520 -- Creating a file package for local directory '/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E5/DASK_ON_REISA/reduction/P8-SN4-LS536-GS4294-I20-AN4-D2025-03-10_22-49-54'.
2025-03-10 23:14:42,293	INFO packaging.py:347 -- Pushing file package 'gcs://_ray_pkg_cddfbb8ce545aba1.zip' (0.48MiB) to Ray cluster...
2025-03-10 23:14:42,300	INFO packaging.py:360 -- Successfully pushed file package 'gcs://_ray_pkg_cddfbb8ce545aba1.zip'.
RAY_INIT_TIME:       3.61833
Iter [0]
[2m[36m(iter_task pid=3677377, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677377, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677381, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677381, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677380, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677380, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677383, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677383, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677376, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677376, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677379, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677379, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677385, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677385, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677378, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677378, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677382, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677382, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677516, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677516, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677607, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677607, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677924, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677924, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677971, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677971, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677913, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677913, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677775, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677775, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677980, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677980, ip=10.120.203.26)[0m   warnings.warn(
[2m[36m(iter_task pid=3677928, ip=10.120.203.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=3677928, ip=10.120.203.26)[0m   warnings.warn(
Iter [2]
Iter [4]
Iter [6]
Iter [8]
Iter [10]
Iter [12]
Iter [14]
Iter [16]
Iter [18]
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m 2025-03-10 23:23:07,199	WARNING worker.py:2519 -- Local object store memory usage:
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m 
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m (global lru) capacity: 72000000000
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m (global lru) used: 29.8262%
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m (global lru) num objects: 3
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m (global lru) num evictions: 493
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m (global lru) bytes evicted: 306759939465
[2m[36m(iter_task pid=3677909, ip=10.120.203.26)[0m 
WARNING: 4 PYTHON worker processes have been started on node: 294cb2054bbe7e8322710c8325df0528156b063779bcb15957e428a7 with address: 172.30.203.37. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m 2025-03-10 23:23:08,164	WARNING worker.py:2519 -- Local object store memory usage:
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m 
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m (global lru) capacity: 72000000000
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m (global lru) used: 29.8262%
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m (global lru) num objects: 3
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m (global lru) num evictions: 493
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m (global lru) bytes evicted: 306759939465
[2m[36m(iter_task pid=3677384, ip=10.120.203.26)[0m 
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m 2025-03-10 23:23:11,033	WARNING worker.py:2519 -- Local object store memory usage:
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m 
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m (global lru) capacity: 72000000000
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m (global lru) used: 40.2654%
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m (global lru) num objects: 4
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m (global lru) num evictions: 493
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m (global lru) bytes evicted: 306759939465
[2m[36m(iter_task pid=3677769, ip=10.120.203.26)[0m 
The node with node id: c1d98a4441760226c32b388650ae348532d4354530fba38a797afa64 and address: 172.30.203.42 and node name: 172.30.203.42 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
EST_ANALYTICS_TIME:  516.36948 (avg:25.81847)
Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E5/DASK_ON_REISA/reduction/P8-SN4-LS536-GS4294-I20-AN4-D2025-03-10_22-49-54/reduction.py", line 56, in <module>
    result = handler.get_result(process_func, iter_func, selected_iters=iterations, kept_iters=max_iterations,
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E5/DASK_ON_REISA/reduction/P8-SN4-LS536-GS4294-I20-AN4-D2025-03-10_22-49-54/reisa.py", line 127, in get_result
    tmp = ray.get(results)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/worker.py", line 434, in get
    res = self._get(to_get, op_timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/worker.py", line 462, in _get
    raise err
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/server/server.py", line 489, in _get_object
    items = ray.get(objectrefs, timeout=request.timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2521, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray::iter_task()[39m (pid=3677384, ip=172.30.203.26)
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E5/DASK_ON_REISA/reduction/P8-SN4-LS536-GS4294-I20-AN4-D2025-03-10_22-49-54/reisa.py", line 116, in iter_task
    current_results_list = ray.get(current_results_list)  # type: #List[dask.array.core.Array]
ray.exceptions.OwnerDiedError: Failed to retrieve object 460893864ad4c66bffffffffffffffffffffffff0400000001000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*dac036dde420f3cfd707d60b49a2e0f49ddda1bc41c8fea9ad876964*` at IP address 172.30.203.39) for more information about the Python worker failure.
srun: error: ilk-121: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=10933989.10
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 10933989 ON ilk-120 CANCELLED AT 2025-03-10T23:34:17 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 10933989.11 ON ilk-133 CANCELLED AT 2025-03-10T23:34:17 DUE TO TIME LIMIT ***
*** SIGTERM received at time=1741646057 on cpu 20 ***
*** SIGTERM received at time=1741646057 on cpu 2 ***
*** SIGTERM received at time=1741646057 on cpu 16 ***
*** SIGTERM received at time=1741646057 on cpu 17 ***
*** SIGTERM received at time=1741646057 on cpu 37 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x1534b72002f4 while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1741646057 on cpu 37 ***
