slurmstepd: info: Setting TMPDIR to /scratch/10772508. Previous errors about TMPDIR can be discarded
Slurm job started at 26/02/2025_12:34:28 AM

In transit.
Initing Ray (1 head node + 2 worker nodes + 2 simulation nodes) on nodes: 
	ilk-65 ilk-67 ilk-68 ilk-69 ilk-82
Head node: 172.30.202.17:6379


RAY_DEPLOY_TIME:     22.89138
RAY_INIT_TIME:       3.31685
Iter [0]
2025-02-26 00:34:55,359	INFO packaging.py:520 -- Creating a file package for local directory '/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E1/DASK_ON_REISA/reduction/P4-SN2-LS536-GS2147-I25-AN2-D2025-02-25_20-31-21'.
2025-02-26 00:34:55,387	INFO packaging.py:347 -- Pushing file package 'gcs://_ray_pkg_1854d82659bb5e47.zip' (0.48MiB) to Ray cluster...
2025-02-26 00:34:55,393	INFO packaging.py:360 -- Successfully pushed file package 'gcs://_ray_pkg_1854d82659bb5e47.zip'.
Iter [2]
Iter [4]
Iter [6]
Iter [8]
Iter [10]
Iter [12]
Iter [14]
Iter [16]
Iter [18]
The node with node id: 376eb53190cb83e1d796cf5b9d2f0f9c130e054f3b0906b74393d3cd and address: 172.30.202.34 and node name: 172.30.202.34 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
EST_ANALYTICS_TIME:  191.19313 (avg:7.64773)
Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E1/DASK_ON_REISA/reduction/P4-SN2-LS536-GS2147-I25-AN2-D2025-02-25_20-31-21/reduction.py", line 56, in <module>
    result = handler.get_result(process_func, iter_func, selected_iters=iterations, kept_iters=max_iterations,
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E1/DASK_ON_REISA/reduction/P4-SN2-LS536-GS2147-I25-AN2-D2025-02-25_20-31-21/reisa.py", line 127, in get_result
    tmp = ray.get(results)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/worker.py", line 434, in get
    res = self._get(to_get, op_timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/worker.py", line 462, in _get
    raise err
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/server/server.py", line 489, in _get_object
    items = ray.get(objectrefs, timeout=request.timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2521, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray::iter_task()[39m (pid=480656, ip=172.30.202.20)
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E1/DASK_ON_REISA/reduction/P4-SN2-LS536-GS2147-I25-AN2-D2025-02-25_20-31-21/reisa.py", line 113, in iter_task
    current_results = ray.get(current_results)  # type: #List[List[ray._raylet.ObjectRef]]
ray.exceptions.ActorUnschedulableError: The actor is not schedulable: The node specified via NodeAffinitySchedulingStrategy doesn't exist any more or is infeasible, and soft=False was specified.
srun: error: ilk-67: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=10772508.6
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 10772508 ON ilk-65 CANCELLED AT 2025-02-26T00:54:45 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 10772508.7 ON ilk-69 CANCELLED AT 2025-02-26T00:54:45 DUE TO TIME LIMIT ***
*** SIGTERM received at time=1740527685 on cpu 35 ***
*** SIGTERM received at time=1740527685 on cpu 33 ***
*** SIGTERM received at time=1740527685 on cpu 32 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x153abd63b1b7 while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1740527685 on cpu 33 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x1535cc87954c while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1740527685 on cpu 32 ***
